In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import warnings 
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('IPL stats 2008-27.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278205 entries, 0 to 278204
Data columns (total 64 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         278205 non-null  int64
 1   match_id           278205 non-null  int64
 2   date               278205 non-null  object
 3   match_type         278205 non-null  object
 4   event_name         278205 non-null  object
 5   innings            278205 non-null  int64
 6   batting_team       278205 non-null  object
 7   bowling_team       278205 non-null  object
 8   over               278205 non-null  int64
 9   ball               278205 non-null  int64
 10  ball_no            278205 non-null  float64
 11  batter             278205 non-null  object
 12  bat_pos            278205 non-null  int64
 13  runs_batter        278205 non-null  int64
 14  balls_faced        278205 non-null  int64
 15  bowler             278205 non-null  object
 16  valid_ball         278205 non-null  int64
 17  runs_extras        278205 non-null  int64
 18  runs_total         278205 non-null  int64
 19  runs_bowler        278205 non-null  int64
 20  runs_not_boundary  278205 non-null  bool
 21  extra_type         15133 non-null   object
 22  non_striker        278205 non-null  object
 23  non_striker_pos    278205 non-null  int64
 24  wicket_kind        13823 non-null   object
 25  player_out         13823 non-null   object
 26  fielders           10013 non-null   object
 27  runs_target        133903 non-null  float64
 28  review_batter      872 non-null     object
 29  team_reviewed      872 non-null     object
 30  review_decision    872 non-null     object
 31  umpire             872 non-null     object
 32  umpires_call       278205 non-null  bool
 33  player_of_match    278205 non-null  object
 34  match_won_by       278205 non-null  object
 35  win_outcome        273503 non-null  object
 36  toss_winner        278205 non-null  object
 37  toss_decision      278205 non-null  object
 38  venue              278205 non-null  object
 39  city               278205 non-null  object
 40  day                278205 non-null  int64
 41  month              278205 non-null  int64
 42  year               278205 non-null  int64
 43  season             278205 non-null  object
 44  gender             278205 non-null  object
 45  team_type          278205 non-null  object
 46  superover_winner   3896 non-null    object
 47  result_type        4702 non-null    object
 48  method             3890 non-null    object
 49  balls_per_over     278205 non-null  int64
 50  overs              278205 non-null  int64
 51  event_match_no     278205 non-null  object
 52  stage              278205 non-null  object
 53  match_number       278205 non-null  object
 54  team_runs          278205 non-null  int64
 55  team_balls         278205 non-null  int64
 56  team_wicket        278205 non-null  int64
 57  new_batter         13321 non-null   object
 58  batter_runs        278205 non-null  int64
 59  batter_balls       278205 non-null  int64
 60  bowler_wicket      278205 non-null  int64
 61  batting_partners   278205 non-null  object
 62  next_batter        13321 non-null   object
 63  striker_out        278205 non-null  bool
dtypes: bool(3), float64(2), int64(24), object(35)
memory usage: 130.3+ MB

In [4]:
df.head()

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,131970,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,131971,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,131972,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,131973,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,131974,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [19]:
df.columns.to_list()

['Unnamed: 0',
 'match_id',
 'date',
 'match_type',
 'event_name',
 'innings',
 'batting_team',
 'bowling_team',
 'over',
 'ball',
 'ball_no',
 'batter',
 'bat_pos',
 'runs_batter',
 'balls_faced',
 'bowler',
 'valid_ball',
 'runs_extras',
 'runs_total',
 'runs_bowler',
 'runs_not_boundary',
 'extra_type',
 'non_striker',
 'non_striker_pos',
 'wicket_kind',
 'player_out',
 'fielders',
 'runs_target',
 'review_batter',
 'team_reviewed',
 'review_decision',
 'umpire',
 'umpires_call',
 'player_of_match',
 'match_won_by',
 'win_outcome',
 'toss_winner',
 'toss_decision',
 'venue',
 'city',
 'day',
 'month',
 'year',
 'season',
 'gender',
 'team_type',
 'superover_winner',
 'result_type',
 'method',
 'balls_per_over',
 'overs',
 'event_match_no',
 'stage',
 'match_number',
 'team_runs',
 'team_balls',
 'team_wicket',
 'new_batter',
 'batter_runs',
 'batter_balls',
 'bowler_wicket',
 'batting_partners',
 'next_batter',
 'striker_out']

In [20]:
df.shape

(278205, 64)

In [21]:
print("Matches:", df['match_id'].nunique())
print("Seasons:", df['season'].nunique())
print("Teams:", df['batting_team'].nunique())
print("Batters:", df['batter'].nunique())
print("Bowlers:", df['bowler'].nunique())
print("Venues:", df['venue'].nunique())

Matches: 1169
Seasons: 22
Teams: 19
Batters: 703
Bowlers: 550
Venues: 59

In [22]:
missing = df.isnull().sum()
missing = missing[missing>0]
missing.sort_values(ascending=False)

team_reviewed       277333
review_batter       277333
review_decision     277333
umpire              277333
method              274315
superover_winner    274309
result_type         273503
fielders            268192
new_batter          264884
next_batter         264884
wicket_kind         264382
player_out          264382
extra_type          263072
runs_target         144302
win_outcome           4702
dtype: int64

In [23]:
missing_pct = (df.isnull().sum())/(len(df))

missing_pct = missing_pct[missing_pct>0]

missing_pct.sort_values(ascending=False)

team_reviewed       0.996866
review_batter       0.996866
review_decision     0.996866
umpire              0.996866
method              0.986018
superover_winner    0.985996
result_type         0.983099
fielders            0.964009
new_batter          0.952118
next_batter         0.952118
wicket_kind         0.950314
player_out          0.950314
extra_type          0.945605
runs_target         0.518689
win_outcome         0.016901
dtype: float64

In [24]:
df.describe()

,Unnamed: 0,match_id,innings,over,ball,ball_no,bat_pos,runs_batter,balls_faced,valid_ball,...,month,year,balls_per_over,overs,team_runs,team_balls,team_wicket,batter_runs,batter_balls,bowler_wicket
count,278205.000000,2.782050e+05,278205.000000,278205.000000,278205.000000,278205.000000,278205.000000,278205.000000,278205.000000,278205.000000,...,278205.000000,278205.000000,278205.0,278205.0,278205.000000,278205.000000,278205.000000,278205.000000,278205.000000,278205.000000
mean,139102.000000,9.422687e+05,1.482914,9.193839,3.488855,9.542725,3.612555,1.277378,0.967362,0.963182,...,4.787933,2016.710178,6.0,20.0,77.110498,58.614637,2.456972,18.327424,14.011211,0.045470
std,80311.010157,3.817198e+05,0.502571,5.681511,1.708263,5.682938,2.168978,1.651107,0.177687,0.188315,...,1.586724,5.248572,0.0,0.0,49.957873,34.117619,2.100374,18.578093,11.833930,0.208333
min,0.000000,3.359820e+05,1.000000,0.000000,1.000000,0.100000,1.000000,0.000000,0.000000,0.000000,...,3.000000,2008.000000,6.0,20.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,69551.000000,5.483530e+05,1.000000,4.000000,2.000000,4.500000,2.000000,0.000000,1.000000,1.000000,...,4.000000,2012.000000,6.0,20.0,36.000000,29.000000,1.000000,4.000000,5.000000,0.000000
50%,139102.000000,1.082601e+06,1.000000,9.000000,3.000000,9.400000,3.000000,1.000000,1.000000,1.000000,...,4.000000,2017.000000,6.0,20.0,73.000000,58.000000,2.000000,12.000000,11.000000,0.000000
75%,208653.000000,1.304049e+06,2.000000,14.000000,5.000000,14.400000,5.000000,1.000000,1.000000,1.000000,...,5.000000,2022.000000,6.0,20.0,113.000000,88.000000,4.000000,27.000000,20.000000,0.000000
max,278204.000000,1.485779e+06,6.000000,19.000000,7.000000,19.600000,11.000000,6.000000,1.000000,1.000000,...,11.000000,2025.000000,6.0,20.0,287.000000,121.000000,10.000000,175.000000,73.000000,1.000000

In [25]:
df.sample(5)

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
103583,235553,734007,2014-05-14,T20,Indian Premier League,1,Sunrisers Hyderabad,Kings XI Punjab,0,3,...,5,3,0,NaN,0,1,0,"('AJ Finch', 'S Dhawan')",NaN,False
213353,76755,1304068,2022-04-12,T20,Indian Premier League,2,Royal Challengers Bangalore,Chennai Super Kings,14,4,...,134,88,6,PWH de Silva,1,1,0,"('KD Karthik', 'PWH de Silva')",NaN,False
147941,11343,1082639,2017-05-09,T20,Indian Premier League,2,Kolkata Knight Riders,Kings XI Punjab,18,3,...,140,111,6,NaN,0,1,0,"('C de Grandhomme', 'CR Woakes')",NaN,False
210611,74013,1304057,2022-04-03,T20,Indian Premier League,2,Chennai Super Kings,Punjab Kings,1,1,...,5,7,0,NaN,4,5,0,"('RD Gaikwad', 'RV Uthappa')",NaN,False
165237,28639,1175358,2019-03-24,T20,Indian Premier League,1,Delhi Capitals,Mumbai Indians,5,2,...,41,32,2,NaN,11,14,0,"('CA Ingram', 'S Dhawan')",NaN,False

In [27]:
df = df.drop(columns=["Unnamed: 0"])

In [28]:
df['date'] = pd.to_datetime(df['date'])

In [31]:
df['date'].dtype

dtype('<M8[ns]')

In [32]:
df.groupby('innings')['runs_target'].apply(lambda x:x.notnull().mean())

innings
1    0.0
2    1.0
3    0.0
4    0.0
5    0.0
6    0.0
Name: runs_target, dtype: float64